import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Phần Header lặp lại */}
        <header className="h-14 flex justify-between items-center px-4">
          <nav>Logo</nav>
          <nav>Login</nav>
        </header>

        {/* Phần Main: Chứa nội dung thay đổi của từng page */}
        <main className="min-h-screen">
            {children}
        </main>

        {/* Phần Footer lặp lại */}
        <footer className="h-10 border-t">
          Copyright 2024
        </footer>
      </body>
    </html>
  );
}
